// import { TrendingMovies } from "@/interfaces/TrendingMovies";

// export const TRENDING_MOVIES: TrendingMovies = {
//   page: 1,
//   results: [
//     {
//       backdrop_path: "/3xN4vNPWBSVDsiiOzL5sB95Sa1J.jpg",
//       id: 257094,
//       title: "Holland",
//       original_title: "Holland",
//       overview:
//         "Nancy is a teacher whose life with her husband in Holland, Michigan, tumbles into a twisted tale when she and her colleague become suspicious of a secret.",
//       poster_path: "/39jIr3A4ScUeGxFdMeARYKNxTgU.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [53, 9648],
//       popularity: 214.0209,
//       release_date: "2025-03-27",
//       video: false,
//       vote_average: 5.608,
//       vote_count: 102,
//     },
//     {
//       backdrop_path: "/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg",
//       id: 1197306,
//       title: "A Working Man",
//       original_title: "A Working Man",
//       overview:
//         "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
//       poster_path: "/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [28, 80, 53],
//       popularity: 266.2088,
//       release_date: "2025-03-26",
//       video: false,
//       vote_average: 7,
//       vote_count: 52,
//     },
//     {
//       backdrop_path: "/sulUXRukzh7WSK34y8mnaUcHo3y.jpg",
//       id: 1254786,
//       title: "The Life List",
//       original_title: "The Life List",
//       overview:
//         "When her mother sends her on a quest to complete a teenage bucket list, a young woman uncovers family secrets, finds romance — and rediscovers herself.",
//       poster_path: "/5fg98cVo7da7OIK45csdLSd4NaU.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [10749, 35, 18],
//       popularity: 171.316,
//       release_date: "2025-03-27",
//       video: false,
//       vote_average: 7.094,
//       vote_count: 64,
//     },
//     {
//       backdrop_path: "/is9bmV6uYXu7LjZGJczxrjJDlv8.jpg",
//       id: 1229730,
//       title: "Carjackers",
//       original_title: "Carjackers",
//       overview:
//         "By day, they're invisible—valets, hostesses, and bartenders at a luxury hotel. By night, they're the Carjackers, a crew of skilled drivers who track and rob wealthy clients on the road. As they plan their ultimate heist, the hotel director hires a ruthless hitman, to stop them at all costs. With danger closing in, can Nora, Zoe, Steve, and Prestance pull off their biggest score yet?",
//       poster_path: "/mtYwRRc7fKt16o0qZJxmBptcdzT.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "fr",
//       genre_ids: [28, 12],
//       popularity: 398.4515,
//       release_date: "2025-03-27",
//       video: false,
//       vote_average: 6.8,
//       vote_count: 18,
//     },
//     {
//       backdrop_path: "/qUc0Hol3eP74dbW4YyqT6oRLYgT.jpg",
//       id: 696506,
//       title: "Mickey 17",
//       original_title: "Mickey 17",
//       overview:
//         "Unlikely hero Mickey Barnes finds himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.",
//       poster_path: "/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [878, 35, 12],
//       popularity: 69.2313,
//       release_date: "2025-02-28",
//       video: false,
//       vote_average: 7,
//       vote_count: 1026,
//     },
//     {
//       backdrop_path: "/u7j9GwAzEuDmYikzhMDWC9kCAiG.jpg",
//       id: 447273,
//       title: "Snow White",
//       original_title: "Snow White",
//       overview:
//         "Princess Snow White flees the castle when the Evil Queen, in her jealousy over Snow White's inner beauty, tries to kill her. Deep into the dark woods, she stumbles upon seven magical dwarves and a young thief named Jonathan. Together, they strive to survive the Queen's relentless pursuit and aspire to take back the kingdom in the process...",
//       poster_path: "/xWWg47tTfparvjK0WJNX4xL8lW2.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [10751, 14],
//       popularity: 258.1002,
//       release_date: "2025-03-19",
//       video: false,
//       vote_average: 4.4,
//       vote_count: 424,
//     },
//     {
//       backdrop_path: "/aJZ33UhVlInyFENbH4GK4s0k6E0.jpg",
//       id: 774100,
//       title:
//         "Alexander and the Terrible, Horrible, No Good, Very Bad Road Trip",
//       original_title:
//         "Alexander and the Terrible, Horrible, No Good, Very Bad Road Trip",
//       overview:
//         "Eleven-year-old Alexander and his family embark on a dream Spring Break vacation to Mexico City only to have all their plans go terribly wrong when they discover a cursed idol.",
//       poster_path: "/srOAe7Xe2KN4QZDSoALmE9T8Hh6.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [35, 10751],
//       popularity: 40.1156,
//       release_date: "2025-03-26",
//       video: false,
//       vote_average: 6.417,
//       vote_count: 18,
//     },
//     {
//       backdrop_path: "/1w8kutrRucTd3wlYyu5QlUDMiG1.jpg",
//       id: 762509,
//       title: "Mufasa: The Lion King",
//       original_title: "Mufasa: The Lion King",
//       overview:
//         "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
//       poster_path: "/lurEK87kukWNaHd0zYnsi3yzJrs.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [12, 10751, 16],
//       popularity: 238.3487,
//       release_date: "2024-12-18",
//       video: false,
//       vote_average: 7.5,
//       vote_count: 1801,
//     },
//     {
//       backdrop_path: "/wM2Yxpihaz8ZJDXYlO1mrgyfI8f.jpg",
//       id: 1124620,
//       title: "The Monkey",
//       original_title: "The Monkey",
//       overview:
//         "When twin brothers find a mysterious wind-up monkey, a series of outrageous deaths tear their family apart. Twenty-five years later, the monkey begins a new killing spree forcing the estranged brothers to confront the cursed toy.",
//       poster_path: "/yYa8Onk9ow7ukcnfp2QWVvjWYel.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [27, 35],
//       popularity: 108.6636,
//       release_date: "2025-02-14",
//       video: false,
//       vote_average: 5.9,
//       vote_count: 315,
//     },
//     {
//       backdrop_path: "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
//       id: 950387,
//       title: "A Minecraft Movie",
//       original_title: "A Minecraft Movie",
//       overview:
//         "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
//       poster_path: "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [10751, 35, 12, 14],
//       popularity: 104.9938,
//       release_date: "2025-03-31",
//       video: false,
//       vote_average: 7.1,
//       vote_count: 16,
//     },
//     {
//       backdrop_path: "/2n7lYEeIbucsEQCswRcVB6ZYmMP.jpg",
//       id: 777443,
//       title: "The Electric State",
//       original_title: "The Electric State",
//       overview:
//         "An orphaned teen hits the road with a mysterious robot to find her long-lost brother, teaming up with a smuggler and his wisecracking sidekick.",
//       poster_path: "/1TZ9Er1xEAKizzKKqYVgJIhNkN2.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [878, 12, 28],
//       popularity: 117.1809,
//       release_date: "2025-03-07",
//       video: false,
//       vote_average: 6.6,
//       vote_count: 858,
//     },
//     {
//       backdrop_path: "/zdy3h2sMppVp1Q41HpLiyF5w7es.jpg",
//       id: 823219,
//       title: "Flow",
//       original_title: "Straume",
//       overview:
//         "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
//       poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "lv",
//       genre_ids: [16, 14, 12],
//       popularity: 82.3994,
//       release_date: "2024-08-29",
//       video: false,
//       vote_average: 8.256,
//       vote_count: 1694,
//     },
//     {
//       backdrop_path: "/8eifdha9GQeZAkexgtD45546XKx.jpg",
//       id: 822119,
//       title: "Captain America: Brave New World",
//       original_title: "Captain America: Brave New World",
//       overview:
//         "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
//       poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [28, 53, 878],
//       popularity: 425.1221,
//       release_date: "2025-02-12",
//       video: false,
//       vote_average: 6.089,
//       vote_count: 1149,
//     },
//     {
//       backdrop_path: "/9p2tVEEWw1M92Pt63Vbq7EjBpvk.jpg",
//       id: 1084199,
//       title: "Companion",
//       original_title: "Companion",
//       overview:
//         "During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.",
//       poster_path: "/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [35, 27, 878, 53],
//       popularity: 101.8967,
//       release_date: "2025-01-22",
//       video: false,
//       vote_average: 7.1,
//       vote_count: 914,
//     },
//     {
//       backdrop_path: "/sNx1A3822kEbqeUxvo5A08o4N7o.jpg",
//       id: 1195506,
//       title: "Novocaine",
//       original_title: "Novocaine",
//       overview:
//         "When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.",
//       poster_path: "/xmMHGz9dVRaMY6rRAlEX4W0Wdhm.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [28, 35, 53],
//       popularity: 45.4325,
//       release_date: "2025-03-12",
//       video: false,
//       vote_average: 7,
//       vote_count: 121,
//     },
//     {
//       backdrop_path: "/4MNRH73XmwBK2ycv3qvLpa07O5F.jpg",
//       id: 1257960,
//       title: "Sikandar",
//       original_title: "सिकंदर",
//       overview:
//         "After his deceased wife’s organs are donated to three different people, a bereaved man sets out to meet them and change their lives, but a corrupt politician stands in the way.",
//       poster_path: "/41s42CRXafa3OuRGvCtfYPEBmse.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "hi",
//       genre_ids: [28, 53],
//       popularity: 15.1789,
//       release_date: "2025-03-29",
//       video: false,
//       vote_average: 6,
//       vote_count: 1,
//     },
//     {
//       backdrop_path: "/tkRDTu9hyWgaBSSzfkYDCZYd1kV.jpg",
//       id: 974576,
//       title: "Conclave",
//       original_title: "Conclave",
//       overview:
//         "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
//       poster_path: "/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [18, 53, 9648],
//       popularity: 29.8987,
//       release_date: "2024-10-25",
//       video: false,
//       vote_average: 7.2,
//       vote_count: 1737,
//     },
//     {
//       backdrop_path: "/zo8CIjJ2nfNOevqNajwMRO6Hwka.jpg",
//       id: 1241982,
//       title: "Moana 2",
//       original_title: "Moana 2",
//       overview:
//         "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
//       poster_path: "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [16, 12, 10751, 35],
//       popularity: 220.0556,
//       release_date: "2024-11-21",
//       video: false,
//       vote_average: 7.1,
//       vote_count: 2097,
//     },
//     {
//       backdrop_path: "/om7apkYMeZMsZ60RsR9DGitTkPy.jpg",
//       id: 804862,
//       title: "Bring Them Down",
//       original_title: "Bring Them Down",
//       overview:
//         "When the ongoing rivalry between farmers Michael and Jack suddenly escalates, it triggers a chain of events that take increasingly violent and devastating turns, leaving both families permanently altered.",
//       poster_path: "/2jskL5eOFTQknpRalJ4chVYyuFo.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [18, 53],
//       popularity: 30.6887,
//       release_date: "2025-02-06",
//       video: false,
//       vote_average: 6.8,
//       vote_count: 16,
//     },
//     {
//       backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
//       id: 1138194,
//       title: "Heretic",
//       original_title: "Heretic",
//       overview:
//         "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
//       poster_path: "/fr96XzlzsONrQrGfdLMiwtQjott.jpg",
//       media_type: "movie",
//       adult: false,
//       original_language: "en",
//       genre_ids: [27, 53],
//       popularity: 41.2591,
//       release_date: "2024-10-31",
//       video: false,
//       vote_average: 7.1,
//       vote_count: 1450,
//     },
//   ],
//   total_pages: 500,
//   total_results: 10000,
// };
